### PR TITLE
Added property to configure push notifications permission

### PR DESCRIPTION
**Pull request by developer2311**
Added ability to manage push notifications permission request showing at the first launch.

### CODE REVIEW

**Comment by developer2311** [comment]
@bensmiley Hi! Can you review my pull request, please?

**Comment by developer2311** [comment]
@bensmiley Thank you for the quick help! I'll happy cooperate with you in future.

**Comment by bensmiley** [comment]
Thanks for the contribution!

**Comment by developer2311** [comment]
Welcome

**Pull request merged**
